
--부서번호가 30이고 영업사원인 직원만 올리시오
SELECT * FROM emp WHERE deptno = 30 AND job = 'SALESMAN';

--부서번호 30에 CLERK인 직원 출력
SELECT * FROM EMP WHERE JOB = 'CLERK';

--연봉이 36000인 직원을 출력하시오
SELECT * FROM emp WHERE sal*12 = 36000;

--F로 시작하는 이름들 출력
SELECT * FROM emp WHERE ENAME LIKE 'F%';

SELECT * FROM emp WHERE ename <= 'F';

SELECT * FROM emp WHERE sal <> 3000;        
SELECT * FROM emp WHERE sal ^= 3000;
SELECT * FROM emp WHERE NOT sal = 3000;

SELECT * FROM emp WHERE job NOT IN ('SALESMAN', 'CLERK');


SELECT * FROM EMP WHERE JOB IN ('MANAGER', 'ANALYST', 'PRESIDENT') AND SAL > 2000 ORDER BY JOB ASC, SAL DESC;

SELECT * FROM EMP WHERE DEPTNO IN (10,30) ORDER BY DEPTNO, ENAME;

SELECT * FROM EMP WHERE SAL IN (1250, 1500, 3000) ORDER BY SAL ASC;

SELECT * FROM EMP WHERE JOB IN ('MANAGER','ANALYST') ORDER BY DEPTNO ASC; 

SELECT * FROM EMP e WHERE JOB IN (MANAGER, ANALYST), IN (20,30) ORDER BY EMPNO ASC;